### ISSUE TITLE
Adding the amlight/coloring and amlight/sdntrace

### ISSUE THREAD

**Issue by jab1982** [amlight/kytos-docker#1]
@italovalcy , can you add these napps to the compose file?

python3 -m pip install -e git+https://github.com/amlight/coloring#egg=coloring
python3 -m pip install -e git+https://github.com/amlight/sdntrace#egg=sdntrace

**Comment by italovalcy** [comment]
Hi @jab1982, both napps are failing to install through pip and the pipeline returned failed.

I've opened the issues https://github.com/amlight/coloring/issues/5 and https://github.com/amlight/sdntrace/issues/1 so we can work on fixing the installation process for coloring and sdntrace napps.

**Comment by viniarck** [comment]
As of Nov 2023, both of these NApps are already part of the docker images. 

I'll close this issue.
