### ISSUE TITLE
Decide on `handlers.RotatingFileHandler` or external tools like `logrotate` 

### ISSUE THREAD

**Issue by viniarck** [amlight/kytos-docker#16]
This is to capture this initial thread with @italovalcy, on this PR https://github.com/kytos-ng/kytos/pull/211#discussion_r877413305, this is for deciding if well use `handlers.RotatingFileHandler` or external tools like `logrotate` 

Currently, logging.ini file handler is using `FileHandler` (it doesn't provide any rotations) https://github.com/amlight/kytos-docker/blob/master/logging.ini#L14, but it's something that the team wants to make sure it's covered for production.

cc'ing @italovalcy

**Comment by italovalcy** [comment]
@viniarck that is a good question and maybe we can leverage a combination of both strategies. The advantage of using `RotatingFileHandler` is to make the application robust enough itself and fault-tolerant against disk full errors, which is great I believe. On the other hand, the admin/operator may want to use `logrotate` to rotate files at certain timed intervals and also compress files (which is not supported by `TimedRotatingFileHandler `).

My suggestion is that we go ahead with `RotatingFileHandler ` on our `logging.ini` file, leaving us safe against non-configured logrotate environments. In this case, I would suggest some like `maxBytes=200MB`, backupCount=3. Wdyt?

**Comment by viniarck** [comment]
> @viniarck that is a good question and maybe we can leverage a combination of both strategies. The advantage of using `RotatingFileHandler` is to make the application robust enough itself and fault-tolerant against disk full errors, which is great I believe. On the other hand, the admin/operator may want to use `logrotate` to rotate files at certain timed intervals and also compress files (which is not supported by `TimedRotatingFileHandler `).
> 
> My suggestion is that we go ahead with `RotatingFileHandler ` on our `logging.ini` file, leaving us safe against non-configured logrotate environments. In this case, I would suggest some like `maxBytes=200MB`, backupCount=3. Wdyt?

Sounds great @italovalcy. Also, with 200MB we should be able to have 1M+ lines on every log file assuming that on average each log line takes 150 bytes, that coupled with Filebeat reading from it seems like a great default value too, so also providing locally sufficient log stored data for worst case scenarios
